server:
  port: 8080
spring:
  mail:
    host: mail
    username: admin@cheerfun.dev
    password: Cheerfun.dev
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
  redis:
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 0 # 连接池中的最小空闲连接
    cluster:
      nodes:
        - redis1:6379
        - redis2:6380
        - redis3:6381
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: root
    password: root
  datasource:
    url: jdbc:mysql://mysql:3306/pixivic?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Cheerfun.dev
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    batch:
      job:
        enabled: false
  cache:
    caffeine:
      spec: maximumSize=1024,expireAfterAccess=1800s
    type: caffeine
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
jjwt:
  secret: 生蚝QAQ只是一位兴趣使然的面向ACG编程人员(●'◡'●)ﾉ♥♥♥♥♥♥
  expirationTime: 864000
  refreshInterval: 1800000
pixiv:
  oauth:
    client_id: KzEZED7aC0vird8jWyHM38mXjNTY
    client_secret: W9JZoJe00qPvJsiyCGT3CCtC6ZUtdpKpzMbNlUGP
    device_token: fb12e7c1945000850deb5f7001c02745
    config: /Users/oysterqaq/PIC/user2.json
saucenao:
  token:
    path: /Users/oysterqaq/PIC/saucenao.json
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: dev.cheerfun.pixivic.common.util.json
elasticsearch:
  ip: elasticsearch
apiLog:
  path: /Users/oysterqaq/Desktop
sensitiveWordList:
  path: /Users/oysterqaq/PIC/sensitive
ssh:
  configPath: /Users/oysterqaq/PIC/ssh.conf
sitemap:
  savePath: /Users/oysterqaq/PIC/sitemap/
  remoteSavePath: /home/sitemap
